[package]
name = "fcss"
version = "0.1.0"
authors = ["李国志 <guozhi.li@dmall.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
nom = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
clap = "*"